name: CI
on:
  push:
    branches: [ main ] # Możesz ograniczyć do głównej gałęzi
    tags-ignore: [ 'v*.*.*' ] # Ignoruj tagi tutaj, bo mają własny workflow
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/run-validation.yml